kind: ConfigMap 
apiVersion: v1 
metadata:
  name: aws-secret 
data:
  # Configuration values can be set as key-value properties
  aws_access_key: YXdzX2FjY2Vzc19rZXlfaWQ9QUtJQVZDNVdQTTVRSVlENTNPM1IKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5PVRUamppQTZFQXJoL3lyZkNwVFVnVURFZksxRkhzb2hXQWU3Z2dLMDk=