kind: Secret 
apiVersion: v1 
metadata:
  name: aws-secret 
data:  
  credentials: YXdzX2FjY2Vzc19rZXlfaWQgPSBBS0lBMldQTklOVFIzSktKS0FEMwphd3Nfc2VjcmV0X2FjY2Vzc19rZXkgPSA4UTdxMHBiaERUNlhSYkcveDVSNVVaNlJ0WTlTQ0NWRW9MQUtSWG9HCg==